### PR TITLE
[l10n]> New pot + New French files

### PR DESCRIPTION
**Pull request by fxbenard**
Can you consider that PR, your plugin is used in Mina olen by Sami. So our French users need that translation.
Thanks

### CODE REVIEW

**Comment by samikeijonen** [comment]
I'll say big yes to this :+1:

**Comment by fxbenard** [comment]
Any news on that, only time seems to be moving. Thanks

**Comment by justintadlock** [comment]
It'd be great if you could send over a patch or create a PR against the 0.1 branch.  The master branch is the latest stable branch.

**Comment by fxbenard** [comment]
@justintadlock It's done

**Pull request merged**
